//
//  RNControlsWidgets.swift
//  react-native-ios-controls
//
//  Add this file to your WIDGET EXTENSION target only. It declares the reusable
//  control templates; your own `Controls.swift` declares which controls exist.
//
//  Do not edit — regenerated by `npx react-native-ios-controls init`.
//

import AppIntents
import SwiftUI
import WidgetKit

// MARK: - Value provider

/// Feeds a control template with state read from the App Group.
///
/// `previewValue` is what the add-a-control gallery renders, so it never blocks
/// on storage; `currentValue()` is what the live control renders.
@available(iOS 18.0, *)
public struct RNControlValueProvider: ControlValueProvider {
  public let kind: String
  public let fallback: RNControlState

  public init(kind: String, fallback: RNControlState) {
    self.kind = kind
    self.fallback = fallback
  }

  public var previewValue: RNControlState { fallback }

  public func currentValue() async throws -> RNControlState {
    RNControlStore.state(kind, fallback: fallback)
  }
}

// MARK: - Color

extension Color {
  /// Parses `#RGB`, `#RRGGBB` and `#RRGGBBAA`. Returns nil for anything else.
  init?(rnHex hex: String?) {
    guard var raw = hex?.trimmingCharacters(in: .whitespacesAndNewlines) else { return nil }
    if raw.hasPrefix("#") { raw.removeFirst() }
    if raw.count == 3 {
      raw = raw.map { "\($0)\($0)" }.joined()
    }
    guard raw.count == 6 || raw.count == 8, let value = UInt64(raw, radix: 16) else { return nil }
    let hasAlpha = raw.count == 8
    let r = Double((value >> (hasAlpha ? 24 : 16)) & 0xFF) / 255
    let g = Double((value >> (hasAlpha ? 16 : 8)) & 0xFF) / 255
    let b = Double((value >> (hasAlpha ? 8 : 0)) & 0xFF) / 255
    let a = hasAlpha ? Double(value & 0xFF) / 255 : 1
    self.init(.sRGB, red: r, green: g, blue: b, opacity: a)
  }
}

// MARK: - Templates

/// A Control Center toggle whose label, symbol, tint and value come from the
/// App Group, so JavaScript can restyle it at runtime.
///
/// ```swift
/// @available(iOS 18.0, *)
/// struct FocusControl: ControlWidget {
///   var body: some ControlWidgetConfiguration {
///     rnToggleControl(
///       kind: "focus",
///       displayName: "Focus",
///       description: "Turn Focus on or off.",
///       defaultState: RNControlState(value: false, title: "Focus", sfSymbol: "moon.fill")
///     )
///   }
/// }
/// ```
@available(iOS 18.0, *)
public func rnToggleControl(
  kind: String,
  displayName: LocalizedStringResource,
  description: LocalizedStringResource,
  defaultState: RNControlState
) -> some ControlWidgetConfiguration {
  StaticControlConfiguration(
    kind: kind,
    provider: RNControlValueProvider(kind: kind, fallback: defaultState)
  ) { state in
    ControlWidgetToggle(
      state.title ?? kind,
      isOn: state.value ?? false,
      action: RNSetControlValueIntent(kind: kind)
    ) { isOn in
      Label(
        state.subtitle ?? (isOn ? "On" : "Off"),
        systemImage: state.sfSymbol ?? "circle"
      )
    }
    .tint(Color(rnHex: state.tint) ?? .accentColor)
  }
  .displayName(displayName)
  .description(description)
}

/// A Control Center button that brings your app to the foreground when pressed.
///
/// The press is reported by `getInitialControlEvent()` on a cold start and to
/// every `addControlEventListener` subscriber.
///
/// ```swift
/// @available(iOS 18.0, *)
/// struct QuickCaptureControl: ControlWidget {
///   var body: some ControlWidgetConfiguration {
///     rnButtonControl(
///       kind: "quickCapture",
///       displayName: "Quick Capture",
///       description: "Open the app and start a note.",
///       defaultState: RNControlState(title: "Capture", sfSymbol: "bolt.fill")
///     )
///   }
/// }
/// ```
@available(iOS 18.0, *)
public func rnButtonControl(
  kind: String,
  displayName: LocalizedStringResource,
  description: LocalizedStringResource,
  defaultState: RNControlState
) -> some ControlWidgetConfiguration {
  StaticControlConfiguration(
    kind: kind,
    provider: RNControlValueProvider(kind: kind, fallback: defaultState)
  ) { state in
    ControlWidgetButton(action: RNOpenAppControlIntent(kind: kind)) {
      Label(state.title ?? kind, systemImage: state.sfSymbol ?? "circle")
    }
    .tint(Color(rnHex: state.tint) ?? .accentColor)
  }
  .displayName(displayName)
  .description(description)
}

/// A Control Center button that records a press *without* opening your app.
///
/// The press is queued in the App Group; your listeners receive it the next
/// time the app becomes active. Use this for fire-and-forget actions that do
/// not need any UI.
///
/// `ControlWidgetTemplateBuilder` does not accept `if`/`else`, and the two
/// intents are distinct Swift types, so opening and silent buttons are separate
/// functions rather than one function with a flag.
@available(iOS 18.0, *)
public func rnSilentButtonControl(
  kind: String,
  displayName: LocalizedStringResource,
  description: LocalizedStringResource,
  defaultState: RNControlState
) -> some ControlWidgetConfiguration {
  StaticControlConfiguration(
    kind: kind,
    provider: RNControlValueProvider(kind: kind, fallback: defaultState)
  ) { state in
    ControlWidgetButton(action: RNPressControlIntent(kind: kind)) {
      Label(state.title ?? kind, systemImage: state.sfSymbol ?? "circle")
    }
    .tint(Color(rnHex: state.tint) ?? .accentColor)
  }
  .displayName(displayName)
  .description(description)
}
