# frozen_string_literal: true

# Adds a WidgetKit control extension to an existing React Native iOS project.
#
# Invoked by `cli/index.js`; not meant to be run directly. Every mutation is
# applied to an in-memory Xcodeproj object and written once at the end, after a
# timestamped backup of the original .pbxproj.

begin
  require 'xcodeproj'
rescue LoadError
  warn <<~MSG
    error: the `xcodeproj` gem is not available.

    It normally ships with CocoaPods. Try one of:
      gem install xcodeproj
      bundle exec pod --version   (if your project uses a Gemfile)
  MSG
  exit 1
end

require 'json'
require 'fileutils'

options = JSON.parse($stdin.read)

PROJECT_PATH   = options.fetch('projectPath')
EXTENSION_NAME = options.fetch('extensionName')
APP_GROUP      = options['appGroup']
PACKAGE_IOS    = options.fetch('packageIosDir')
DRY_RUN        = options.fetch('dryRun', false)
FORCE          = options.fetch('force', false)

def abort_with(message)
  warn "error: #{message}"
  exit 1
end

summary = []

project = Xcodeproj::Project.open(PROJECT_PATH)
project_dir = File.dirname(PROJECT_PATH)

app_target = project.targets.find do |t|
  t.respond_to?(:product_type) && t.product_type == 'com.apple.product-type.application'
end
abort_with("no application target found in #{PROJECT_PATH}") if app_target.nil?

existing = project.targets.find { |t| t.name == EXTENSION_NAME }
if existing && !FORCE
  abort_with(
    "target \"#{EXTENSION_NAME}\" already exists in this project.\n" \
    "       Setup is idempotent by refusing to run twice — nothing was changed.\n" \
    '       Delete the target in Xcode first if you want to re-create it.'
  )
end

app_config = app_target.build_configurations.first
app_bundle_id = app_config.resolve_build_setting('PRODUCT_BUNDLE_IDENTIFIER') ||
                app_config.build_settings['PRODUCT_BUNDLE_IDENTIFIER']
abort_with('could not read the app target PRODUCT_BUNDLE_IDENTIFIER') if app_bundle_id.nil?

app_group = APP_GROUP || "group.#{app_bundle_id}"
ext_bundle_id = "#{app_bundle_id}.controls"
swift_version = app_config.build_settings['SWIFT_VERSION'] || '5.0'
development_team = app_config.build_settings['DEVELOPMENT_TEAM']

ext_dir = File.join(project_dir, EXTENSION_NAME)
shared_dir = File.join(project_dir, 'ReactNativeIosControls')

summary << "app target            #{app_target.name} (#{app_bundle_id})"
summary << "extension target      #{EXTENSION_NAME} (#{ext_bundle_id})"
summary << "app group             #{app_group}"
summary << "extension sources     #{File.join(EXTENSION_NAME, '')}"
summary << "shared sources        #{File.join('ReactNativeIosControls', '')}"

# ---------------------------------------------------------------- file bodies

info_plist = <<~PLIST
  <?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  <plist version="1.0">
  <dict>
  \t<key>CFBundleDevelopmentRegion</key>
  \t<string>$(DEVELOPMENT_LANGUAGE)</string>
  \t<key>CFBundleDisplayName</key>
  \t<string>#{EXTENSION_NAME}</string>
  \t<key>CFBundleExecutable</key>
  \t<string>$(EXECUTABLE_NAME)</string>
  \t<key>CFBundleIdentifier</key>
  \t<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
  \t<key>CFBundleInfoDictionaryVersion</key>
  \t<string>6.0</string>
  \t<key>CFBundleName</key>
  \t<string>$(PRODUCT_NAME)</string>
  \t<key>CFBundlePackageType</key>
  \t<string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
  \t<key>CFBundleShortVersionString</key>
  \t<string>1.0</string>
  \t<key>CFBundleVersion</key>
  \t<string>1</string>
  \t<key>NSExtension</key>
  \t<dict>
  \t\t<key>NSExtensionPointIdentifier</key>
  \t\t<string>com.apple.widgetkit-extension</string>
  \t</dict>
  </dict>
  </plist>
PLIST

entitlements = <<~PLIST
  <?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  <plist version="1.0">
  <dict>
  \t<key>com.apple.security.application-groups</key>
  \t<array>
  \t\t<string>#{app_group}</string>
  \t</array>
  </dict>
  </plist>
PLIST

config_swift = <<~SWIFT
  //
  //  RNControlsConfig.swift
  //  Generated by `npx react-native-ios-controls init`.
  //
  //  Belongs to BOTH the app target and the #{EXTENSION_NAME} target.
  //

  enum RNControlsConfig {
    /// Must match the `appGroup` you pass to `configure()` in JavaScript.
    static let appGroup = "#{app_group}"
  }
SWIFT

controls_swift = <<~SWIFT
  //
  //  Controls.swift
  //  #{EXTENSION_NAME}
  //
  //  This file is yours to edit — declare one `ControlWidget` per control you
  //  want to offer, then list them all in the `WidgetBundle` at the bottom.
  //
  //  A control's `kind` is the identifier you use from JavaScript in
  //  `setControlState(kind, ...)` and the one you receive on `ControlEvent.kind`.
  //

  import SwiftUI
  import WidgetKit

  @available(iOS 18.0, *)
  struct FocusControl: ControlWidget {
    var body: some ControlWidgetConfiguration {
      rnToggleControl(
        kind: "focus",
        displayName: "Focus",
        description: "Turn Focus on or off without unlocking your phone.",
        defaultState: RNControlState(
          value: false,
          title: "Focus",
          sfSymbol: "moon.fill",
          tint: "#7C5CFF"
        )
      )
    }
  }

  @available(iOS 18.0, *)
  struct QuickCaptureControl: ControlWidget {
    var body: some ControlWidgetConfiguration {
      rnButtonControl(
        kind: "quickCapture",
        displayName: "Quick Capture",
        description: "Open the app and start a new note.",
        defaultState: RNControlState(
          title: "Capture",
          sfSymbol: "bolt.fill",
          tint: "#22D3A7"
        )
      )
    }
  }

  @main
  @available(iOS 18.0, *)
  struct #{EXTENSION_NAME}Bundle: WidgetBundle {
    var body: some Widget {
      FocusControl()
      QuickCaptureControl()
    }
  }
SWIFT

files_to_write = {
  File.join(ext_dir, 'Info.plist') => info_plist,
  File.join(ext_dir, "#{EXTENSION_NAME}.entitlements") => entitlements,
  File.join(ext_dir, 'Controls.swift') => controls_swift,
  File.join(shared_dir, 'RNControlsConfig.swift') => config_swift,
  File.join(shared_dir, 'RNControlsShared.swift') =>
    File.read(File.join(PACKAGE_IOS, 'ControlWidgets', 'RNControlsShared.swift')),
  File.join(ext_dir, 'RNControlsWidgets.swift') =>
    File.read(File.join(PACKAGE_IOS, 'ControlWidgets', 'RNControlsWidgets.swift'))
}

# -------------------------------------------------- app target entitlements

app_entitlements_rel = app_config.build_settings['CODE_SIGN_ENTITLEMENTS']
app_entitlements_created = false
if app_entitlements_rel.nil? || app_entitlements_rel.empty?
  app_entitlements_rel = File.join(app_target.name, "#{app_target.name}.entitlements")
  app_entitlements_created = true
end
app_entitlements_abs = File.join(project_dir, app_entitlements_rel)

app_entitlements_plist =
  if File.exist?(app_entitlements_abs)
    Xcodeproj::Plist.read_from_path(app_entitlements_abs) || {}
  else
    {}
  end
groups = app_entitlements_plist['com.apple.security.application-groups'] || []
already_had_group = groups.include?(app_group)
groups |= [app_group]
app_entitlements_plist['com.apple.security.application-groups'] = groups

summary << if already_had_group
             "app entitlements      #{app_entitlements_rel} (already had the group)"
           elsif app_entitlements_created
             "app entitlements      #{app_entitlements_rel} (created)"
           else
             "app entitlements      #{app_entitlements_rel} (group added)"
           end

if DRY_RUN
  puts 'Dry run — nothing was written.'
  puts
  summary.each { |line| puts "  #{line}" }
  puts
  puts '  files that would be created:'
  files_to_write.each_key { |path| puts "    #{path.sub("#{project_dir}/", '')}" }
  puts "    #{app_entitlements_rel}" if app_entitlements_created
  puts
  puts '  Xcode project changes:'
  puts "    + target #{EXTENSION_NAME} (app extension, iOS 18.0)"
  puts "    + \"Embed Foundation Extensions\" build phase on #{app_target.name}"
  puts "    + RNControlsConfig.swift / RNControlsShared.swift on BOTH targets"
  exit 0
end

# ------------------------------------------------------------------- write

backup = "#{PROJECT_PATH}/project.pbxproj.backup-#{Time.now.strftime('%Y%m%d%H%M%S')}"
FileUtils.cp("#{PROJECT_PATH}/project.pbxproj", backup)
summary << "backup                #{File.basename(backup)}"

FileUtils.mkdir_p(ext_dir)
FileUtils.mkdir_p(shared_dir)
files_to_write.each do |path, contents|
  File.write(path, contents)
end
Xcodeproj::Plist.write_to_path(app_entitlements_plist, app_entitlements_abs)

# ------------------------------------------------------------- xcode target

if FORCE
  project.targets.select { |t| t.name == EXTENSION_NAME }.each do |stale|
    # Detach every reference to the target before dropping it. Removing the
    # target on its own leaves the app's PBXTargetDependency pointing at
    # nothing, and the next add_dependency then dies on a nil target.
    project.targets.each do |other|
      other.dependencies.delete_if { |dep| dep.target.nil? || dep.target.uuid == stale.uuid }
      other.copy_files_build_phases.each do |phase|
        phase.files
             .select { |file| file.file_ref == stale.product_reference }
             .each(&:remove_from_project)
      end
    end
    stale.remove_from_project
  end
end

# Also sweep dependencies left dangling by a target someone deleted in Xcode.
app_target.dependencies.delete_if { |dep| dep.target.nil? }

ext_target = project.new_target(:app_extension, EXTENSION_NAME, :ios, '18.0')

ext_group = project.main_group.find_subpath(EXTENSION_NAME, true)
ext_group.set_source_tree('SOURCE_ROOT')
ext_group.set_path(EXTENSION_NAME)

shared_group = project.main_group.find_subpath('ReactNativeIosControls', true)
shared_group.set_source_tree('SOURCE_ROOT')
shared_group.set_path('ReactNativeIosControls')

shared_refs = %w[RNControlsConfig.swift RNControlsShared.swift].map do |name|
  shared_group.find_file_by_path(name) || shared_group.new_reference(name)
end
ext_refs = %w[Controls.swift RNControlsWidgets.swift].map do |name|
  ext_group.find_file_by_path(name) || ext_group.new_reference(name)
end
ext_group.new_reference('Info.plist') unless ext_group.find_file_by_path('Info.plist')

ext_target.add_file_references(ext_refs + shared_refs)

# The intents must exist in the app binary too — see RNControlsShared.swift.
app_sources = app_target.source_build_phase
shared_refs.each do |ref|
  next if app_sources.files_references.include?(ref)

  app_target.add_file_references([ref])
end

embed_phase = app_target.copy_files_build_phases.find { |p| p.name == 'Embed Foundation Extensions' }
if embed_phase.nil?
  embed_phase = app_target.new_copy_files_build_phase('Embed Foundation Extensions')
  embed_phase.symbol_dst_subfolder_spec = :plug_ins
  embed_phase.dst_path = ''
end
embed_phase.files
           .select { |file| file.display_name == "#{EXTENSION_NAME}.appex" }
           .each(&:remove_from_project)
embed_file = embed_phase.add_file_reference(ext_target.product_reference)
embed_file.settings = { 'ATTRIBUTES' => ['RemoveHeadersOnCopy'] }
app_target.add_dependency(ext_target)

ext_target.build_configurations.each do |config|
  config.build_settings.merge!(
    'PRODUCT_BUNDLE_IDENTIFIER' => ext_bundle_id,
    'PRODUCT_NAME' => '$(TARGET_NAME)',
    'INFOPLIST_FILE' => "#{EXTENSION_NAME}/Info.plist",
    'CODE_SIGN_ENTITLEMENTS' => "#{EXTENSION_NAME}/#{EXTENSION_NAME}.entitlements",
    'GENERATE_INFOPLIST_FILE' => 'NO',
    'IPHONEOS_DEPLOYMENT_TARGET' => '18.0',
    'SWIFT_VERSION' => swift_version,
    'TARGETED_DEVICE_FAMILY' => '1,2',
    'SKIP_INSTALL' => 'YES',
    'CURRENT_PROJECT_VERSION' => '1',
    'MARKETING_VERSION' => '1.0',
    'LD_RUNPATH_SEARCH_PATHS' => ['$(inherited)', '@executable_path/Frameworks',
                                  '@executable_path/../../Frameworks']
  )
  config.build_settings['DEVELOPMENT_TEAM'] = development_team if development_team
end

app_target.build_configurations.each do |config|
  config.build_settings['CODE_SIGN_ENTITLEMENTS'] = app_entitlements_rel
end

project.save

# ------------------------------------------------------------------ report

puts 'Added a WidgetKit control extension.'
puts
summary.each { |line| puts "  #{line}" }
puts
puts '  created'
files_to_write.each_key { |path| puts "    #{path.sub("#{project_dir}/", '')}" }
puts
puts '  next'
puts '    1. cd ios && pod install'
puts "    2. In Xcode, confirm the #{EXTENSION_NAME} scheme builds"
puts "    3. Call configure({ appGroup: '#{app_group}' }) on app start"
