//
//  RNControlsConfig.swift
//  Generated by `npx react-native-ios-controls init`.
//
//  Belongs to BOTH the app target and the ControlsExtension target.
//

enum RNControlsConfig {
  /// Must match the `appGroup` you pass to `configure()` in JavaScript.
  static let appGroup = "group.ioscontrols.example"
}
