//
//  RNControlsShared.swift
//  react-native-ios-controls
//
//  Add this file to BOTH your app target and your widget extension target.
//
//  Target membership is not a style choice here: an `AppIntent` that opens the
//  app must be compiled into the app as well, otherwise iOS rejects the press
//  with "openAppWhenRun is not supported in extensions" and your button does
//  nothing. `react-native-ios-controls init` sets both memberships for you.
//
//  Do not edit — regenerated by `npx react-native-ios-controls init`.
//

import AppIntents
import Foundation

// MARK: - State

/// The renderable state of one control, mirrored from JavaScript's `ControlState`.
public struct RNControlState: Codable, Sendable {
  public var value: Bool?
  public var title: String?
  public var subtitle: String?
  public var sfSymbol: String?
  public var tint: String?

  public init(
    value: Bool? = nil,
    title: String? = nil,
    subtitle: String? = nil,
    sfSymbol: String? = nil,
    tint: String? = nil
  ) {
    self.value = value
    self.title = title
    self.subtitle = subtitle
    self.sfSymbol = sfSymbol
    self.tint = tint
  }

  /// Returns a copy where every field set on `self` wins over `fallback`.
  public func merging(over fallback: RNControlState) -> RNControlState {
    RNControlState(
      value: value ?? fallback.value,
      title: title ?? fallback.title,
      subtitle: subtitle ?? fallback.subtitle,
      sfSymbol: sfSymbol ?? fallback.sfSymbol,
      tint: tint ?? fallback.tint
    )
  }
}

/// One recorded interaction, mirrored from JavaScript's `ControlEvent`.
public struct RNControlEvent: Codable, Sendable {
  public var kind: String
  public var action: String
  public var value: Bool?
  public var id: String
  public var timestamp: Double
}

// MARK: - Store

/// Reads and writes the App Group storage shared by the app and this extension.
///
/// The app side of this store lives in the library's CocoaPods target
/// (`RNIosControlsStore`); a widget extension cannot link that pod, so the two
/// implementations are deliberately separate and share only the on-disk format
/// documented in `docs/how-controls-work.md`.
public enum RNControlStore {

  /// Most recent events are kept; older ones are dropped once the queue is full.
  public static let maxQueuedEvents = 32

  private static let statePrefix = "rnic.state."
  private static let eventsKey = "rnic.events"
  private static let launchEventKey = "rnic.launchEvent"

  private static var defaults: UserDefaults? {
    UserDefaults(suiteName: RNControlsConfig.appGroup)
  }

  // MARK: State

  public static func state(_ kind: String, fallback: RNControlState = RNControlState())
    -> RNControlState
  {
    guard let raw = defaults?.string(forKey: statePrefix + kind),
      let data = raw.data(using: .utf8),
      let decoded = try? JSONDecoder().decode(RNControlState.self, from: data)
    else { return fallback }
    return decoded.merging(over: fallback)
  }

  public static func setValue(_ kind: String, _ value: Bool) {
    var current = state(kind)
    current.value = value
    write(kind, current)
  }

  public static func write(_ kind: String, _ state: RNControlState) {
    guard let data = try? JSONEncoder().encode(state),
      let raw = String(data: data, encoding: .utf8)
    else { return }
    defaults?.set(raw, forKey: statePrefix + kind)
  }

  // MARK: Events

  /// Appends an interaction to the queue the app drains when it next runs.
  ///
  /// - Parameter isLaunchEvent: also record it as the event that opened the app,
  ///   so `getInitialControlEvent()` can report a cold start.
  public static func record(
    kind: String,
    action: String,
    value: Bool? = nil,
    isLaunchEvent: Bool = false
  ) {
    let event = RNControlEvent(
      kind: kind,
      action: action,
      value: value,
      id: UUID().uuidString,
      timestamp: Date().timeIntervalSince1970 * 1000
    )

    guard let defaults else { return }

    var queue: [RNControlEvent] = []
    if let raw = defaults.string(forKey: eventsKey), let data = raw.data(using: .utf8) {
      queue = (try? JSONDecoder().decode([RNControlEvent].self, from: data)) ?? []
    }
    queue.append(event)
    if queue.count > maxQueuedEvents {
      queue.removeFirst(queue.count - maxQueuedEvents)
    }
    if let data = try? JSONEncoder().encode(queue),
      let raw = String(data: data, encoding: .utf8)
    {
      defaults.set(raw, forKey: eventsKey)
    }

    if isLaunchEvent,
      let data = try? JSONEncoder().encode(event),
      let raw = String(data: data, encoding: .utf8)
    {
      defaults.set(raw, forKey: launchEventKey)
    }
  }
}

// MARK: - Intents

/// Backs every toggle control. WidgetKit runs this inside the extension.
@available(iOS 18.0, *)
public struct RNSetControlValueIntent: SetValueIntent {
  public static var title: LocalizedStringResource = "Set Control Value"

  @Parameter(title: "Control")
  public var kind: String

  @Parameter(title: "Value")
  public var value: Bool

  public init() {}

  public init(kind: String) {
    self.kind = kind
  }

  public func perform() async throws -> some IntentResult {
    RNControlStore.setValue(kind, value)
    RNControlStore.record(kind: kind, action: "toggle", value: value)
    return .result()
  }
}

/// Backs a button control that records a press without opening the app.
@available(iOS 18.0, *)
public struct RNPressControlIntent: AppIntent {
  public static var title: LocalizedStringResource = "Run Control Action"

  @Parameter(title: "Control")
  public var kind: String

  public init() {}

  public init(kind: String) {
    self.kind = kind
  }

  public func perform() async throws -> some IntentResult {
    RNControlStore.record(kind: kind, action: "press")
    return .result()
  }
}

/// Backs a button control that brings the app to the foreground.
///
/// `perform()` runs in the *app* process, which is why this file must belong to
/// the app target too.
@available(iOS 18.0, *)
public struct RNOpenAppControlIntent: AppIntent {
  public static var title: LocalizedStringResource = "Open App From Control"
  public static var openAppWhenRun: Bool = true

  @Parameter(title: "Control")
  public var kind: String

  public init() {}

  public init(kind: String) {
    self.kind = kind
  }

  public func perform() async throws -> some IntentResult {
    RNControlStore.record(kind: kind, action: "press", isLaunchEvent: true)
    return .result()
  }
}
